version: "3.8"

services:
  mongo_db:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017

  project:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    image: project:latest
    links:
      - mongo_db:app_db
    ports:
      - 8080:8080